# Generated by Django 4.0.3 on 2022-03-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('antigüedad', models.DateField(max_length=50)),
                ('desempleado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Freelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=40)),
                ('desempleado', models.BooleanField()),
                ('tarea_asignada', models.CharField(max_length=35)),
                ('fecha_entrega', models.DateTimeField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Permanente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=40)),
                ('desempleado', models.BooleanField()),
                ('sueldo_aportes', models.IntegerField()),
            ],
        ),
    ]
